// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYitjym5kBDC4wIekVA434GeRkW4x7xT0',
    appId: '1:783180619104:web:273df80160b3fbdd055205',
    messagingSenderId: '783180619104',
    projectId: 'kj-amongus-10529',
    authDomain: 'kj-amongus-10529.firebaseapp.com',
    storageBucket: 'kj-amongus-10529.firebasestorage.app',
    measurementId: 'G-BRZE9L9LMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq18bzUo9Va0OMrs6Dous9VQaWZXUmDk4',
    appId: '1:783180619104:android:88eb628d15538a61055205',
    messagingSenderId: '783180619104',
    projectId: 'kj-amongus-10529',
    storageBucket: 'kj-amongus-10529.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1iBDQDcerA-xHZ-zFzhL916iKNu3sJ6c',
    appId: '1:783180619104:ios:02200f13edd6ab7c055205',
    messagingSenderId: '783180619104',
    projectId: 'kj-amongus-10529',
    storageBucket: 'kj-amongus-10529.firebasestorage.app',
    iosBundleId: 'com.example.kjAmongus',
  );
}
